### PR TITLE
An empty project is created

### PR DESCRIPTION
**Pull request by aktasfatih**
I created an empty project in the vibes folder.
bitmoji

### CODE REVIEW

**Review by davidherczeg — COMMENTED** [review]
Add /.idea to the root .gitignore file and remove all the committed files from the .idea folder

**Comment by aktasfatih** [comment]
That should do it.

**Comment by TaylorZowtuk** [comment]
Edit the PR to have devel as the base branch instead of master.
https://help.github.com/en/articles/changing-the-base-branch-of-a-pull-request

**Comment by adriancleung** [comment]
Changed base branch

**Pull request merged**
